export default [
  {
    id: 1,
    title: "Ինչպե՞ս կտրել նակրը բրաուզերի միջոցով",
    slug: "how-to-crop-image-on-browser",
    image: "/static/media/newMain.8b5dc8d8.jpg",
    text: "Lorem Ipsum",
    authorName: "Ստեփան Զորյան",
    date: "Հունիսի 10,2019",
    datetime: "2019-06-10T10:11:37+00:00",
    duration: 3,
  },
  {
    id: 2,
    title: "Որտե՞ղ է թաղված շան գլուխը",
    slug: "how-to-equate-unequal-things",
    image: "/static/media/newMain.8b5dc8d8.jpg",
    text: "Lorem Ipsum",
    authorName: "Արկադի Դումիկյան",
    date: "Օգոստոսի 27,2020",
    datetime: "2020-08-27T10:11:37+00:00",
    duration: 13,
  },
  {
    id: 3,
    title: "Ինչպե՞ս հավասարեցնել անհավասարը բաները",
    slug: "where-is-the-dogs-head",
    image: "/static/media/newMain.8b5dc8d8.jpg",
    text: "Lorem Ipsum",
    authorName: "Հովհաննես Թումանյան",
    date: "Հունիսի 31,2020",
    datetime: "2019-06-31T10:11:37+00:00",
    duration: 113,
  },
];
