export const COURSES_SUCCESS = "COURSES_SUCCESS";
export const LESSONS_SUCCESS = "LESSONS_SUCCESS";
export const COURSES_ERROR = "COURSES_ERROR";
export const COURSES_REQUEST = "COURSES_REQUEST";
export const TAB_PACKAGE_ID = "TAB_PACKAGE_ID";
